# Generated by Django 4.2.1 on 2023-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_buscada', models.CharField(max_length=100)),
                ('cantidad_busquedas', models.PositiveIntegerField(default=0)),
                ('primera_busqueda', models.DateTimeField(auto_now_add=True)),
                ('ultima_busqueda', models.DateTimeField(auto_now=True)),
                ('ultima_cantidad_resultados', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
