# Generated by Django 4.2.1 on 2023-06-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='cantidad_busquedas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='palabra_buscada',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='ultima_cantidad_resultados',
            field=models.IntegerField(default=0),
        ),
    ]
