# Generated by Django 4.2.1 on 2023-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0002_alter_consulta_cantidad_busquedas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='palabra_buscada',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
