# Generated by Django 4.2.1 on 2023-06-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0003_alter_consulta_palabra_buscada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='ultima_cantidad_resultados',
        ),
    ]
